num1 = int(input("Enter First Number:"))
num2 = int(input("Enter another number:"))
print("Addition:", num1 + num2)
print("Substraction:", num1 - num2)
print("Multiplication:", num1 * num2)
print("Division:", num1/num2)